export default function About() {
  return (
    <main
      className="
        flex
        min-h-svh
        w-full
        items-center
        justify-center
        overflow-hidden
        bg-[#111]
        px-4
      "
    >
      <h1
        className="
          text-center
          font-sans
          font-normal
          text-[clamp(2.75rem,14vw,10rem)]
          uppercase
          leading-[1.05]
          tracking-[clamp(0.02rem,0.3vw,0.3rem)]
          text-white
        "
      >
        ABOUT
      </h1>
    </main>
  );
}